
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymllyajjtqdiidbaghzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltbGx5YWpqdHFkaWlkYmFnaHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTY1ODUsImV4cCI6MjA1ODU5MjU4NX0.5DRzrdUAsfylpLNNu7v9ijBTvD6U7ylTGJCGF06bhwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
